// <auto-generated />
using System;
using AspNetCoreVueStarter.Entities.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace AspNetCoreVueStarter.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20191020113434_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("AspNetCoreVueStarter.Entities.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("05827dca-5e88-4449-a765-c4df53f3e267"),
                            Description = "Cash account for our users",
                            OwnerId = new Guid("b75b9284-95df-4ad7-b5fa-accff0effff3"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("8dfe12d9-9688-42c9-9d6b-fc38e32c03da"),
                            Description = "Savings account for our users",
                            OwnerId = new Guid("fab26154-d97e-4657-83ab-a0769340b978"),
                            Type = 1
                        },
                        new
                        {
                            Id = new Guid("1de3a0bb-8f1d-4f4d-a9b5-430d8adb1376"),
                            Description = "Income account for our users",
                            OwnerId = new Guid("fab26154-d97e-4657-83ab-a0769340b978"),
                            Type = 3
                        });
                });

            modelBuilder.Entity("AspNetCoreVueStarter.Entities.Owner", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Owners");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b75b9284-95df-4ad7-b5fa-accff0effff3"),
                            Address = "John Doe's address",
                            Name = "John Doe"
                        },
                        new
                        {
                            Id = new Guid("fab26154-d97e-4657-83ab-a0769340b978"),
                            Address = "Jane Doe's address",
                            Name = "Jane Doe"
                        });
                });

            modelBuilder.Entity("AspNetCoreVueStarter.Entities.Account", b =>
                {
                    b.HasOne("AspNetCoreVueStarter.Entities.Owner", "Owner")
                        .WithMany("Accounts")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
